fix: initial files for script
housingbayarea/bloom pull request #462
Opened 2022-08-19 22:56 UTC by ColinBuyck

2022-09-09 03:06 UTC, jaredcwhite requested changes
I like this functionality and the overall approach! My main request would be to add some comments to the scripts…I could probably figure out the specific steps after some review, but it'd be awesome to outline more of what each logical section is for and how it gets used.

2022-09-09 18:30 UTC, ColinBuyck commented on sites/public/scripts/resource-translations-export.ts
> +const LANGUAGES = "es,zh,vi"
I think since we're running this independently from the next site (internal development use), it'd be easier to keep the flexibility of the explicit variable definition here rather than import a package to allow this to pull from the env variables.

2022-09-09 18:31 UTC, ColinBuyck commented
@jaredcwhite Good point on the commenting! I added those and responded with my thoughts to the ENV question.

2022-09-12 15:17 UTC, emilyjablonski commented on sites/public/scripts/resource-translations-export.csv
> +file,style,lang, title, url, body
Do we need this in the repo?

2022-09-12 15:18 UTC, emilyjablonski approved these changes
Colin and I reviewed offline 👍

2022-09-12 20:58 UTC, ColinBuyck commented on sites/public/scripts/resource-translations-export.csv
> +file,style,lang, title, url, body
Good call! Just removed it 🧹

2022-09-13 16:02 UTC, seanmalbert approved these changes
@ColinBuyck ,
This looks good. There's an edge case for a follow-up PR (not urgent) and I think we want the scripts added to core. So we could have an issue to add to core that also makes that update.

2022-09-13 20:38 UTC, merged