feat: toggle what to expect field based on listing type unless custom
housingbayarea/bloom pull request #468
Opened 2022-09-08 22:59 UTC by emilyjablonski

2022-09-12 14:46 UTC, ludtkemorgan commented on ui-components/src/locales/general.json
> +  "whatToExpect.fcfsReadMore": "<p>Housing preferences, if applicable, will affect first come, first serve order.</p><p className='mt-2'>Your application may be removed if you have made any fraudulen
It appears like this will be the first time we introduce any `className` to a locale file. Do we have any concern that this could be an issue in the future? It would only be an issue if we do a major css upgrade to the app (something like getting rid of tailwind)

2022-09-16 21:38 UTC, ludtkemorgan approved these changes

2022-09-16 21:38 UTC, ludtkemorgan commented on sites/public/src/ListingView.tsx
> +  const whatToExpectContent = getWhatToExpectContent()
What you have here works and I'm ok with it staying this way, but since this is a function that only purpose is to take a listing and return the content/expandable content it would be a good candidate to move outside of the React component. Just above the exported ListingView would work. That way you would gain the *tiniest* bit of performance increase plus make the component slightly more readable and easier to test if you want to write a unit test for it

If you want to go that route all that you would need to change is make `listings` be a passed in parameter. Also I'd recommend adding the return type to the function.

2022-09-16 21:38 UTC, ludtkemorgan commented on ui-components/src/locales/general.json
> +  "whatToExpect.fcfsReadMore": "<p>Housing preferences, if applicable, will affect first come, first serve order.</p><p className='mt-2'>Your application may be removed if you have made any fraudulen
I don't really see any issue with it, but I'd be curious if anyone else has an opinion on it

2022-09-19 22:09 UTC, ColinBuyck commented on ui-components/src/locales/general.json
> +  "whatToExpect.fcfsReadMore": "<p>Housing preferences, if applicable, will affect first come, first serve order.</p><p className='mt-2'>Your application may be removed if you have made any fraudulen
I don't have any strong opinions/concerns on this either.

2022-09-19 23:04 UTC, ColinBuyck requested changes

2022-09-19 23:04 UTC, ColinBuyck commented on backend/core/src/migration/1662677503624-reset-what-to-expect.ts
> +      "Applicants will be contacted by the property agent in rank order until vacancies are filled. All of the information that you have provided will be verified and your eligibility confirmed. Your
I believe this string is missing a sentence of the current default text. It's highlighted in the screenshot below. Let me know if I'm misunderstanding though.
<img width="347" alt="Screen Shot 2022-09-19 at 4 00 40 PM" src="https://user-images.githubusercontent.com/53269332/191134178-146ec6dc-58bf-4cac-9eb8-a474fa2b3c85.png">

2022-09-20 04:16 UTC, jaredcwhite commented on ui-components/src/locales/general.json
> +  "whatToExpect.fcfsReadMore": "<p>Housing preferences, if applicable, will affect first come, first serve order.</p><p className='mt-2'>Your application may be removed if you have made any fraudulen
@ludtkemorgan @emilyjablonski I believe to date we've only had Markdown in locale files, not HTML tags. Many places we disable rendering HTML through the markdown-to-jsx library altogether. Is there a way we can use just Markdown here and not HTML tags?

2022-09-20 15:42 UTC, emilyjablonski commented on ui-components/src/locales/general.json
> +  "whatToExpect.fcfsReadMore": "<p>Housing preferences, if applicable, will affect first come, first serve order.</p><p className='mt-2'>Your application may be removed if you have made any fraudulen
We do have other strings where we're using HTML, but I'm happy to go either way

2022-09-23 13:38 UTC, emilyjablonski commented on backend/core/src/migration/1662677503624-reset-what-to-expect.ts
> +      "Applicants will be contacted by the property agent in rank order until vacancies are filled. All of the information that you have provided will be verified and your eligibility confirmed. Your
@ColinBuyck Good catch thank you!! It looks like both strings are defaults depending on whether or not the listing has preferences, I'll make sure the migration replaces both

2022-09-24 03:53 UTC, jaredcwhite commented
Hmm, I just realized…this is a PR for a Core issue/merge into dev, but it's in the hba repo? Don't we want it upstream?

2022-09-26 15:13 UTC, emilyjablonski commented
@jaredcwhite We want this in HBA because we don't want to default this field in Detroit

2022-09-26 16:27 UTC, ColinBuyck approved these changes
LGTM!

2022-09-27 15:53 UTC, merged