3138/multiselect question x translation issue
housingbayarea/bloom pull request #512
Opened 2022-10-18 06:11 UTC by YazeedLoonat

## Issue Overview

This PR addresses [#issue](https://github.com/bloom-housing/bloom/issues/3138)

- [x] This change addresses only certain aspects of the issue

## Description
This should resolve the creation of a new application where the application is translated into any language besides english.
The problem was that when an application was submitted from the public site while that application was translated into not english the data in the program/preference column would save in the not english language.

This resolves the actual saving of new applications, a follow on pr will come with a migration to clean the data

## How Can This Be Tested/Reviewed?
go to create a new application on the public site
select a language besides english

continue on with the application creation process
1) make sure the application form has translations for the program/preference sections of the application process
2) make sure the review step of the application has the program/preference sections translated
3) make sure you can submit the application
4) on the partner side verify the data that was submitted is present
5) verify the csv export of that application has no column for a program/preference that is translated

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-10-18 14:30 UTC, ludtkemorgan requested changes
I think there might be a slight bug with the code. When I applied to a listing in Spanish it appears to do the translations correctly. However, when I do the CSV export it picked a different (yet very similar) preference to put it in. You can see in this CSV I applied for a listing in san jose with the `Preference Live/Work in County - San Jose` preference. However it put it in the column of `Preference Live/Work in County - Alameda`
![image](https://user-images.githubusercontent.com/42942267/196459289-ccd9f547-e815-4107-9f62-421ec41d933e.png)

2022-10-18 14:30 UTC, ludtkemorgan commented on sites/public/pages/applications/review/terms.tsx
> +import { ApplicationSection, ApplicationReviewStatus } from "@bloom-housing/backend-core"
Looks like you ran into a merge conflict here with my latest changes. You'll want the ListingReviewOrder import as it is used on line 99

2022-10-19 16:41 UTC, YazeedLoonat commented on sites/public/pages/applications/review/terms.tsx
> +import { ApplicationSection, ApplicationReviewStatus } from "@bloom-housing/backend-core"
nice catch, got that updated!

2022-10-19 16:46 UTC, YazeedLoonat commented
Hey @ludtkemorgan so I think the reason for that is the preferences selected on that 
![image](https://user-images.githubusercontent.com/10088764/196753455-e54f8a1e-cb27-4879-9d79-524b4ef4896c.png)
 is because the preference tied to it are the alameda ones so I think that is translating correctly?

2022-10-20 19:25 UTC, ludtkemorgan approved these changes
functionally this looks good. Approving this assuming that the backend-swagger is fixed

2022-10-20 19:25 UTC, ludtkemorgan commented on backend/core/types/src/backend-swagger.ts
> +  retrieve1(
This change is causing a compilation issue since it is expecting `retrieveListings`

2022-10-20 19:25 UTC, ludtkemorgan commented on backend/core/src/multiselect-question/entities/multiselect-question.entity.ts
> +  untranslatedOptoutText?: string
Really minor, but the "O" in "out" should be capitalized

2022-10-24 21:52 UTC, YazeedLoonat commented
I got your updates in here @ludtkemorgan nice catches!

2022-10-25 17:33 UTC, emilyjablonski commented on backend/core/src/translations/services/translations.service.ts
> +        listing.listingMultiselectQuestions[i].multiselectQuestion.options[k].untranslatedText =
Do you need optOutText here?

2022-10-25 17:34 UTC, emilyjablonski commented
Is there a way we can make this fix without updating the data model? Is there a plan to remove the new fields after the fix?

2022-10-25 19:59 UTC, YazeedLoonat commented
Hey @emilyjablonski I think thats a good point, maybe a better approach could be when the data comes back to the server we do untransation work there?

@ludtkemorgan thoughts?

2022-10-27 23:50 UTC, YazeedLoonat commented on backend/core/src/translations/services/translations.service.ts
> +        listing.listingMultiselectQuestions[i].multiselectQuestion.options[k].untranslatedText =
Hey @emilyjablonski I don't think so, up above there is the line `listing.listingMultiselectQuestions[i].multiselectQuestion.untranslatedOptOutText =
        listing.listingMultiselectQuestions[i].multiselectQuestion.optOutText` which I think is correct since multiselect questions don't have opt out text on a per option basis

2022-10-27 23:51 UTC, YazeedLoonat commented
updating from convos: it sounds like we are comfortable making these changes, and then using the follow up spike we can revisit and come up with a better permanent solution

2022-11-01 15:33 UTC, emilyjablonski commented
@YazeedLoonat Do you mind making a ticket with all of the context and the proposed resolution?

2022-11-01 15:47 UTC, YazeedLoonat commented
Hey @emilyjablonski are you asking for: https://github.com/bloom-housing/bloom/issues/3157 

the research spike into this? 
I linked it to the original issue but it should be the follow up issue we had talked about

2022-11-01 16:24 UTC, emilyjablonski commented on backend/core/src/translations/services/translations.service.ts
> +          listing.listingMultiselectQuestions[i].multiselectQuestion.options[k].text
Do you need optOutText here as above?

2022-11-02 17:01 UTC, emilyjablonski approved these changes

2022-11-10 16:48 UTC, merged