chore: add backend translations for Alameda confirmation email
housingbayarea/bloom pull request #542
Opened 2022-11-15 05:08 UTC by jaredcwhite

## Issue Overview

This PR addresses #490

- [ ] This change addresses the issue in full
- [x] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Please include a summary of the change and which issue(s) is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## How Can This Be Tested/Reviewed?

Provide instructions so we can review.

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] I have exported any new pieces added to ui-components
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2022-11-29 16:03 UTC, ludtkemorgan requested changes

2022-11-29 16:03 UTC, ludtkemorgan commented on backend/core/src/migration/1668473259849-addAlaWhatToExpectTranslations.ts
> +    alaSpanish = alaSpanish["0"]["translations"]
This is failing in circle ci and locally because it looks like there isn't an entry in the DB for alameda in Spanish. In fact it looks like there is only 1 Spanish entry and it is for San Jose. Alameda and San Mateo only have entries for English.

2022-11-29 21:18 UTC, jaredcwhite commented on backend/core/src/migration/1668473259849-addAlaWhatToExpectTranslations.ts
> +    alaSpanish = alaSpanish["0"]["translations"]
@ludtkemorgan ah…yeah. So we might need to backtrack on this and look at a more comprehensive plan to add translations of any sort to emails for Alameda & SMC.

2022-12-01 17:44 UTC, kathyccheng commented
Closing until we have translations

2022-12-01 17:44 UTC, closed without merging