Release/2024 02 17
housingbayarea/bloom pull request #664
Opened 2024-02-17 16:36 UTC by ludtkemorgan

# Pull Request Template

## Issue Overview

This PR addresses #issue

- [ ] This change addresses the issue in full
- [ ] This change addresses only certain aspects of the issue
- [ ] This change is a dependency for another issue
- [ ] This change has a dependency from another issue

## Description

Please include a summary of the change and which issue(s) is addressed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## How Can This Be Tested/Reviewed?

Provide instructions so we can review.

Describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have added QA notes to the issue with applicable URLs
- [ ] I have performed a self-review of my own code
- [ ] I have reviewed the changes in a desktop view
- [ ] I have reviewed the changes in a mobile view
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have assigned reviewers
- [ ] I have run `yarn generate:client` and/or created a migration if I made backend changes that require them
- [ ] My commit message(s) is/are polished, and any breaking changes are indicated in the message and are well-described
- [ ] Commits made across packages purposefully have the same commit message/version change, else are separated into different commits

## Reviewer Notes:

Steps to review a PR:

- Read and understand the issue, and ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Also review the acceptance criteria on the Netlify deploy preview (noting that these do not yet include any backend changes made in the PR)
- Either explicitly ask a clarifying question, request changes, or approve the PR if there are small remaining changes but the PR is otherwise good to go

## On Merge:

If you have one commit and message, squash. If you need each message to be applied, rebase and merge.

2024-02-20 16:45 UTC, YazeedLoonat requested changes
This looks fantastic! 
Only thing I found was: 
the user export seems to have a problem where it both doesn't download in the web browser and also  doesn't actually send an email out

2024-02-20 22:25 UTC, emilyjablonski commented on sites/public/src/pages/applications/preferences/all.tsx
> +  const { listing } = useFormConductor("preferencesAll")
Do you know where this change is coming from?

2024-02-20 22:42 UTC, ludtkemorgan commented on sites/public/src/pages/applications/preferences/all.tsx
> +  const { listing } = useFormConductor("preferencesAll")
I'm trying to get the cypress tests to pass and this was a theory since I get a warning about "There is no step defined which matches preferences". That did not solve the issue of running the cypress tests in ci so I'll remove it. But it is a warning that we might want to address at some point.

For the cypress issue. It appears that for some reason only one of the two address verification steps is happening on circleCi when both of them happen when running locally. And they work correctly in Core. So still digging into it

2024-02-21 00:23 UTC, ludtkemorgan commented on sites/public/src/pages/applications/preferences/all.tsx
> +  const { listing } = useFormConductor("preferencesAll")
ok, I reverted this change and I got the cypress public test working. I don't know why it was working locally but it was an issue with additional data in the application data for the cypress test.

2024-02-21 01:36 UTC, ColinBuyck commented
I recognize that this is happening in Core as well but I'm just noticing that export files are saved on the backend. Are there any concerns with doing this with production-level usage? Will it continue to build up over time?
<img width="660" alt="Screenshot 2024-02-20 at 5 29 29 PM" src="https://github.com/housingbayarea/bloom/assets/53269332/7dc04451-6b0f-494e-9b32-839ee8634658">

2024-02-21 02:22 UTC, YazeedLoonat commented
> I recognize that this is happening in Core as well but I'm just noticing that export files are saved on the backend. Is that temp folder automatically deleted at some point? Are there any concerns with doing this with production-level usage? <img alt="Screenshot 2024-02-20 at 5 29 29 PM" width="660" src="https://private-user-images.githubusercontent.com/53269332/306463412-7dc04451-6b0f-494e-9b32-839ee8634658.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0ODIzODQsIm5iZiI6MTcwODQ4MjA4NCwicGF0aCI6Ii81MzI2OTMzMi8zMDY0NjM0MTItN2RjMDQ0NTEtNmIwZi00OTRlLTliMzItODM5ZWU4NjM0NjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDAyMjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YWM5MTAwMzM2N2ZlNDNjYzZjZmQ3ZGNmMjQ0ZmQ1YTE5NWU3MjE1ZTMzYzQyYzVhYjg5NTIwMjQ2MzE2NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HXwUa7byLn0DNcNuntoBfnxBF5MiCUvhFW2GJ2bkqrw">

Hello! we have a cronjob that runs every so often that will clear that folder of all data

we were running into collisions with the testing which indicated that deleting the files immediately could cause issues on production which files being deleted before they were sent

2024-02-21 18:31 UTC, ColinBuyck approved these changes
LGTM 🕹️ Thanks for the clarification @YazeedLoonat!

2024-02-21 19:43 UTC, merged